### ISSUE TITLE
[Bug]: Parch installer menu not opening

### ISSUE THREAD

**Issue by shahriaarrr** [parchlinux/parch-iso-cinnamon#2]
### What happened?

When using parch ISO in virtual box, Welcome menu opens, but it does not open at all through installation option or clicking on the parch installer program ((other programs do not have this problem and only the installer does not open))

### Virtual machine specifications:

- base memory ((RAM)): 10GB
- storage: 100 GB
- processors: 6
- video memory: 93 MB

### In which part of the Parchlinux is there a problem?

APPs

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by behdanisohrab** [comment]
@shahriaarrr try the stable release.

**Comment by behdanisohrab** [comment]
this issue should be solved in the new beta release
